framework:
  assets:
    packages:
      app:
        json_manifest_path: '%kernel.project_dir%/public/build/app/manifest.json'
      admin:
        json_manifest_path: '%kernel.project_dir%/public/build/admin/manifest.json'
