doctrine_migrations:
  migrations_paths:
    'App\Shared\Infrastructure\Doctrine\Migrations': '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Migrations'
    'App\Security\Infrastructure\Doctrine\Migrations': '%kernel.project_dir%/src/Security/Infrastructure/Doctrine/Migrations'
