security:
  enable_authenticator_manager: true
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    security:
      id: App\Security\Infrastructure\Symfony\Security\UserProvider

  encoders:
    App\Security\Infrastructure\Symfony\Security\User:
      algorithm: 'auto'

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      form_login:
        login_path: security_user_login
        check_path: security_user_login
        enable_csrf: true
      logout:
        path: security_user_logout
  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/profile, roles: ROLE_USER }
    - { path: ^/, roles: PUBLIC_ACCESS }
