restaurant:
  resource: ../../src/Restaurant/Admin
  type: annotation
  prefix: /admin

security:
  resource: ../../src/Security/Admin
  type: annotation
  prefix: /admin

shared:
  resource: ../../src/Shared/Admin
  type: annotation
  prefix: /admin
