restaurant:
  resource: ../../src/Restaurant/Application
  type: annotation

security:
  resource: ../../src/Security/Application
  type: annotation

shared:
  resource: ../../src/Shared/Application
  type: annotation
