parameters:
  project_name: 'Cook''N Collect'
  no_reply_address: 'no-reply@cook-and-collect.fr'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $subjectPrefix: '%project_name%'
      string $noReplyAddress: '%no_reply_address%'

  _instanceof:
    App\Shared\Domain\UseCase\UseCaseHandler:
      tags: [ 'messenger.message_handler' ]

  ## Shared
  App\Shared\Application\:
    resource: '../src/Shared/Application'
  App\Shared\Domain\:
    resource: '../src/Shared/Domain'
  App\Shared\Infrastructure\:
    resource: '../src/Shared/Infrastructure'

  ## Security
  App\Security\Application\:
    resource: '../src/Security/Application'
  App\Security\Domain\:
    resource: '../src/Security/Domain'
  App\Security\Infrastructure\:
    resource: '../src/Security/Infrastructure'

